version: '3'

volumes:
  consul-data: {}
  consul-config: {}
  consul-storage: {}

services:
  
  consul:
    image: gliderlabs/consul-server:latest
    network_mode: "host"
    container_name: consul
    hostname: consul
    environment:
      - TZ=America/Sao_Paulo
      - SERVICE_NAME=consul
      - SERVICE_TAGS=dev
      - CONSUL_TOKEN=asdlkj10
    volumes:
      - ./data/consul/data:/consul/data
      - ./data/consul/config:/consul/config
      - ./data/consul/storage:/data
    command: "-node=local -advertise=$MY_IP -bind $MY_IP -server -bootstrap-expect=1 -client 0.0.0.0 -dc localhost" # -retry-join ${MY_IP} -retry-join 10.2.20.231 -retry-join 10.2.20.241"

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    hostname: localhost
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-ip $MY_IP consul://$MY_IP:8500"

  haproxy:
    build: .
    container_name: haproxy-local
    hostname: haproxy-local
    depends_on:
      - consul
      - registrator
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936"
    expose:
      - "80"
      - "443"
      - "1936"
    environment:
      - TZ=America/Sao_Paulo
      - SERVICE_NAME=haproxy
      - SERVICE_TAGS=dev
      - HAPROXY_DOMAIN=localhost
      - HAPROXY_MODE=consul
      - CONSUL_CONNECT=$MY_IP:8500
      - CONSUL_LOGLEVEL=debug
#      - CONSUL_CONFIG=/consul-template/config.d/consul.tmpl
#    volumes:
#      - ./template/consul.tmpl:/consul-template/config.d/consul.tmpl


    
