version: '3'

volumes:
  consul-data: {}
  consul-config: {}
  consul-storage: {}

services:
  
  consul:
    image: gliderlabs/consul-server:latest
    container_name: consul
    hostname: consul
    environment:
      - TZ=America/Sao_Paulo
      - SERVICE_NAME=consul
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301/udp"
      - "8302:8302/udp"
      - "8400:8400"
      - "8600:8600/udp"
    expose:
      - "8500"
      - "8300"
      - "8301/udp"
      - "8302/udp"
      - "8400"
      - "8600/udp"
    volumes:
      - ./data/consul/data:/consul/data
      - ./data/consul/config:/consul/config
      - ./data/consul/storage:/data
    command: "-node=local -advertise=192.168.15.11 -server -bootstrap -client 0.0.0.0 -ui -dc localhost"

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    hostname: localhost
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-ip 192.168.15.11 consul://192.168.15.11:8500"

  haproxy:
    build: .
    container_name: haproxy-local
    hostname: haproxy-local
    depends_on:
      - consul
      - registrator
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936"
    expose:
      - "80"
      - "443"
      - "1936"
    environment:
      - TZ=America/Sao_Paulo
      - SERVICE_NAME=haproxy
      - HAPROXY_COMPRESSION=true
      - HAPROXY_STATS=true
#      - HAPROXY_STATS_TITLE="Haproxy Stats"
#      - HAPROXY_STATS_URI="/stats"
      - HAPROXY_MODE=consul
#      - HAPROXY_DOMAIN=haproxy.service.consul
      - CONSUL_CONNECT=192.168.15.11:8500
      - CONSUL_LOGLEVEL=debug

    
